//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eKuharica.Mobile.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eKuharica.Mobile.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj lajkova.
        /// </summary>
        internal static string BrojLajkova {
            get {
                return ResourceManager.GetString("BrojLajkova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Članci.
        /// </summary>
        internal static string Članci {
            get {
                return ResourceManager.GetString("Članci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desert.
        /// </summary>
        internal static string Desert {
            get {
                return ResourceManager.GetString("Desert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        internal static string Dodaj {
            get {
                return ResourceManager.GetString("Dodaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dojam.
        /// </summary>
        internal static string Dojam {
            get {
                return ResourceManager.GetString("Dojam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hladno predjelo.
        /// </summary>
        internal static string HladnoPredjelo {
            get {
                return ResourceManager.GetString("HladnoPredjelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        internal static string Ime {
            get {
                return ResourceManager.GetString("Ime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Između 1h i 2h.
        /// </summary>
        internal static string Izmedju1hI2h {
            get {
                return ResourceManager.GetString("Izmedju1hI2h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Između 30min i 1h.
        /// </summary>
        internal static string Izmedju30minI1h {
            get {
                return ResourceManager.GetString("Izmedju30minI1h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jednostavno.
        /// </summary>
        internal static string Jednostavno {
            get {
                return ResourceManager.GetString("Jednostavno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juha.
        /// </summary>
        internal static string Juha {
            get {
                return ResourceManager.GetString("Juha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentar.
        /// </summary>
        internal static string Komentar {
            get {
                return ResourceManager.GetString("Komentar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentari.
        /// </summary>
        internal static string Komentari {
            get {
                return ResourceManager.GetString("Komentari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime.
        /// </summary>
        internal static string KorisničkoIme {
            get {
                return ResourceManager.GetString("KorisničkoIme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kruh i peciva.
        /// </summary>
        internal static string KruhIPeciva {
            get {
                return ResourceManager.GetString("KruhIPeciva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka.
        /// </summary>
        internal static string Lozinka {
            get {
                return ResourceManager.GetString("Lozinka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manje od 30min.
        /// </summary>
        internal static string ManjeOd30min {
            get {
                return ResourceManager.GetString("ManjeOd30min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moji recepti.
        /// </summary>
        internal static string MojiRecepti {
            get {
                return ResourceManager.GetString("MojiRecepti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naslov.
        /// </summary>
        internal static string Naslov {
            get {
                return ResourceManager.GetString("Naslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazad.
        /// </summary>
        internal static string Nazad {
            get {
                return ResourceManager.GetString("Nazad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocjena.
        /// </summary>
        internal static string Ocjena {
            get {
                return ResourceManager.GetString("Ocjena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omiljeni recepti.
        /// </summary>
        internal static string OmiljeniRecepti {
            get {
                return ResourceManager.GetString("OmiljeniRecepti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostavi dojam.
        /// </summary>
        internal static string OstaviDojam {
            get {
                return ResourceManager.GetString("OstaviDojam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piće.
        /// </summary>
        internal static string Piće {
            get {
                return ResourceManager.GetString("Piće", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početna.
        /// </summary>
        internal static string Početna {
            get {
                return ResourceManager.GetString("Početna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pošalji recept.
        /// </summary>
        internal static string PošaljiRecept {
            get {
                return ResourceManager.GetString("PošaljiRecept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavke.
        /// </summary>
        internal static string Postavke {
            get {
                return ResourceManager.GetString("Postavke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postupak.
        /// </summary>
        internal static string Postupak {
            get {
                return ResourceManager.GetString("Postupak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi lozinku.
        /// </summary>
        internal static string PotvrdiLozinku {
            get {
                return ResourceManager.GetString("PotvrdiLozinku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prati.
        /// </summary>
        internal static string Prati {
            get {
                return ResourceManager.GetString("Prati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pratim.
        /// </summary>
        internal static string Pratim {
            get {
                return ResourceManager.GetString("Pratim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pratitelji.
        /// </summary>
        internal static string Pratitelji {
            get {
                return ResourceManager.GetString("Pratitelji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        internal static string Prezime {
            get {
                return ResourceManager.GetString("Prezime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pridružio se.
        /// </summary>
        internal static string PridružioSe {
            get {
                return ResourceManager.GetString("PridružioSe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijavi se.
        /// </summary>
        internal static string PrijaviSe {
            get {
                return ResourceManager.GetString("PrijaviSe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prilozi.
        /// </summary>
        internal static string Prilozi {
            get {
                return ResourceManager.GetString("Prilozi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recepti.
        /// </summary>
        internal static string Recepti {
            get {
                return ResourceManager.GetString("Recepti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salata.
        /// </summary>
        internal static string Salata {
            get {
                return ResourceManager.GetString("Salata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sastojci.
        /// </summary>
        internal static string Sastojci {
            get {
                return ResourceManager.GetString("Sastojci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savijet.
        /// </summary>
        internal static string Savijet {
            get {
                return ResourceManager.GetString("Savijet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviranje.
        /// </summary>
        internal static string Serviranje {
            get {
                return ResourceManager.GetString("Serviranje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Složeno.
        /// </summary>
        internal static string Složeno {
            get {
                return ResourceManager.GetString("Složeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sos.
        /// </summary>
        internal static string Sos {
            get {
                return ResourceManager.GetString("Sos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spremi.
        /// </summary>
        internal static string Spremi {
            get {
                return ResourceManager.GetString("Spremi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srednje.
        /// </summary>
        internal static string Srednje {
            get {
                return ResourceManager.GetString("Srednje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sviđa mi se.
        /// </summary>
        internal static string SviđaMiSe {
            get {
                return ResourceManager.GetString("SviđaMiSe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Težina pripreme.
        /// </summary>
        internal static string TežinaPripreme {
            get {
                return ResourceManager.GetString("TežinaPripreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplo predjelo.
        /// </summary>
        internal static string ToploPredjelo {
            get {
                return ResourceManager.GetString("ToploPredjelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uvod.
        /// </summary>
        internal static string Uvod {
            get {
                return ResourceManager.GetString("Uvod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Više od 2h.
        /// </summary>
        internal static string ViseOd2h {
            get {
                return ResourceManager.GetString("ViseOd2h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijeme pripreme.
        /// </summary>
        internal static string VrijemePripreme {
            get {
                return ResourceManager.GetString("VrijemePripreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijeme pripreme (min).
        /// </summary>
        internal static string VrijemePripremeMin {
            get {
                return ResourceManager.GetString("VrijemePripremeMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrsta jela.
        /// </summary>
        internal static string VrstaJela {
            get {
                return ResourceManager.GetString("VrstaJela", resourceCulture);
            }
        }
    }
}
